baseURL = 'https://www.poulikov.ru/'
languageCode = 'en-us'
title = 'Sergey Poulikov'
theme = "devise"
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; Copyright 2023, Sergey Poulikov"


# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post/"
    weight = -100
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -90

# Configuration Features
[params]
  description = "sergey poulikov personal site"      # Your meta description of the site
  header_title = "Sergey Poulikov"                 # Your header title
  header_subtitle = "" # Your header subtitle
  home_image = "/images/avatar.png"          # Path to header image starting from the static directory (optional)
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"        # First-choice font
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "http://github.com/poulikov"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-telegram fa-1x"
    href = "https://t.me/poulikov"
